import type {Topic} from "../types/global";
export let topics: Topic[]=[
	{id: "add", name: "Addition", icon: "+", category: "Arithmetic"},
	{id: "subtrt", name: "Subtraction", icon: "-", category: "Arithmetic"},
	{id: "mult", name: "Multiplication", icon: "×", category: "Arithmetic"},
	{id: "divid", name: "Division", icon: "÷", category: "Arithmetic"},
	{id: "fraction", name: "Fractions", icon: "a/b", category: "Algebra"},
	{id: "percent", name: "Percentages", icon: "%", category: "Algebra"},
	{id: "ratio", name: "Ratios & Proportions", icon: ":", category: "Algebra"},
	{id: "unit_conv", name: "Unit Conversion", icon: "kg→lb", category: "Algebra"},
	{id: "expr_eval", name: "Expression Evaluation", icon: "x→y", category: "Algebra"},
	{id: "number_sets", name: "Number Sets", icon: "N Z Q R", category: "Algebra"},
	{id: "properties", name: "Algebraic Properties", icon: "≡", category: "Algebra"},
	{id: "order_ops", name: "Order of Operations", icon: "()", category: "Algebra"},
	{id: "linear_word", name: "Linear Word Problems", icon: "word", category: "Algebra"},
	{id: "radical_simplify", name: "Simplify Radicals", icon: "√", category: "Algebra"},
	{id: "radical_eq", name: "Radical Equations", icon: "√x=", category: "Algebra"},
	{id: "rational_exp", name: "Rational Exponents", icon: "x^(m/n)", category: "Algebra"},
	{id: "exp_rules", name: "Exponent Rules", icon: "a^m·a^n", category: "Algebra"},
	{id: "sci_notation", name: "Scientific Notation", icon: "×10ⁿ", category: "Algebra"},
	{id: "complex_basic", name: "Complex Numbers", icon: "a+bi", category: "Algebra"},
	{id: "variation", name: "Direct/Inverse Variation", icon: "∝", category: "Algebra"},
	{id: "real_ops", name: "Real Number Ops", icon: "| |", category: "Algebra"},
	{id: "cartesian", name: "Cartesian Plane", icon: "(x,y)", category: "Algebra"},
	{id: "linear_special", name: "Special Linear Eq", icon: "=?=", category: "Algebra"},
	{id: "rational_eq", name: "Rational Equations", icon: "x/1", category: "Algebra"},
	{id: "root", name: "Roots", icon: "√", category: "Algebra"},
	{id: "log", name: "Logarithm", icon: "log", category: "Algebra"},
	{id: "exp", name: "Exponential", icon: "eˣ", category: "Algebra"},
	{id: "fact", name: "Factorial", icon: "!", category: "Algebra"},
	{id: "ser", name: "Series", icon: "Σ", category: "Algebra"},
	{id: "func_props", name: "Function Props", icon: "f()", category: "Algebra"},
	{id: "basic_funcs", name: "Basic Functions", icon: "f(x) B", category: "Algebra"},
	{id: "func_ops", name: "Function Ops", icon: "f∘g", category: "Algebra"},
	{id: "inverse_funcs", name: "Inverse Funcs", icon: "f⁻¹", category: "Algebra"},
	{id: "transformations", name: "Transformations", icon: "↔", category: "Algebra"},
	{id: "power_model", name: "Power Model", icon: "xⁿ", category: "Algebra"},
	{id: "poly_ineq", name: "Polynomial Ineq", icon: ">", category: "Algebra"},
	{id: "poly_end", name: "Poly End Behavior", icon: "↗↘", category: "Algebra"},
	{id: "synth_div", name: "Synthetic Div", icon: "÷ₛ", category: "Algebra"},
	{id: "complex_zeros", name: "Complex Zeros", icon: "i", category: "Algebra"},
	{id: "rational_analysis", name: "Rational Graphs", icon: "1/x", category: "Algebra"},
	{id: "circle_eq", name: "Circle Equations", icon: "◯ E", category: "Algebra"},
	{id: "logistic", name: "Logistic Funcs", icon: "S", category: "Algebra"},
	{id: "exp_model", name: "Exp Modeling", icon: "eᵗ", category: "Algebra"},
	{id: "log_model", name: "Log Modeling", icon: "log(t)", category: "Algebra"},
	{id: "finance", name: "Finance", icon: "$", category: "Algebra"},
	// New algebra topics
	{id: "linear_eq", name: "Linear Equations", icon: "ax+b=c", category: "Algebra"},
	{id: "quadratic_eq", name: "Quadratic Equations", icon: "ax²+bx+c=0", category: "Algebra"},
	{id: "linear_ineq", name: "Linear Inequalities", icon: "x>y", category: "Algebra"},
	{id: "quadratic_ineq", name: "Quadratic Inequalities", icon: "x²>4", category: "Algebra"},
	{id: "rational_ineq", name: "Rational Inequalities", icon: "(x-1)/(x+2)>0", category: "Algebra"},
	{id: "system2x2", name: "2×2 Systems", icon: "{ax+by=c}", category: "Algebra"},
	{id: "poly_ops", name: "Polynomial Operations", icon: "+ - ×", category: "Algebra"},
	{id: "poly_div", name: "Polynomial Division", icon: "÷", category: "Algebra"},
	{id: "factoring", name: "Factoring", icon: "(x+a)(x+b)", category: "Algebra"},
	{id: "func_concepts", name: "Function Concepts", icon: "domain/range", category: "Algebra"},
	{id: "linear_graph", name: "Linear Graphs", icon: "y=mx+b", category: "Algebra"},
	{id: "nonlinear_graph", name: "Non‑Linear Graphs", icon: "parabola", category: "Algebra"},
	// Calculus
	{id: "lim", name: "Limits", icon: "lim", category: "Calculus"},
	{id: "deri", name: "Differentiation", icon: "∂", category: "Calculus"},
	{id: "inte", name: "Integration", icon: "∫", category: "Calculus"},
	{id: "relRates", name: "Related Rates", icon: "dx/dt", category: "Calculus"},
	{id: "limits_continuity", name: "Limits & Continuity", icon: "limC", category: "Calculus"},
	{id: "applications_diff", name: "Applications of Diff", icon: "appD", category: "Calculus"},
	{id: "integration_advanced", name: "Advanced Integration", icon: "intA", category: "Calculus"},
	{id: "graphical_calculus", name: "Graphical Calculus", icon: "graph", category: "Calculus"},
	{id: "parametric_polar", name: "Parametric/Polar", icon: "param", category: "Calculus"},
	{id: "sequences_series", name: "Sequences & Series", icon: "series", category: "Calculus"},
	// Linear Algebra
	{id: "mtrx", name: "Matrix Operations", icon: "[ ]", category: "Linear Algebra"},
	{id: "vctr", name: "Vector Operations", icon: "→", category: "Linear Algebra"},
	{id: "system3x3", name: "3x3 Systems", icon: "3×3", category: "Linear Algebra"},
	{id: "row_echelon3x3", name: "Row Echelon", icon: "REF", category: "Linear Algebra"},
	{id: "partial_fractions", name: "Partial Fractions", icon: "1/(x+a)", category: "Linear Algebra"},
	{id: "linear_programming", name: "Linear Programming", icon: "LP", category: "Linear Algebra"},
	{id: "vector3d", name: "3D Vectors", icon: "⟨x,y,z⟩", category: "Linear Algebra"},
	{id: "line3d", name: "3D Lines", icon: "L3", category: "Linear Algebra"},
	{id: "plane3d", name: "3D Planes", icon: "⌂", category: "Linear Algebra"},
	// Trigonometry
	{id: "sin", name: "Sine", icon: "sin", category: "Trigonometry"},
	{id: "cos", name: "Cosine", icon: "cos", category: "Trigonometry"},
	{id: "tan", name: "Tangent", icon: "tan", category: "Trigonometry"},
	{id: "cosec", name: "Cosecant", icon: "csc", category: "Trigonometry"},
	{id: "sec", name: "Secant", icon: "sec", category: "Trigonometry"},
	{id: "cot", name: "Cotangent", icon: "cot", category: "Trigonometry"},
	{id: "trig_graph", name: "Trig Graphs", icon: "f(x)", category: "Trigonometry"},
	{id: "deg_to_rad", name: "Degrees → Radians", icon: "°→rad", category: "Trigonometry"},
	{id: "rad_to_deg", name: "Radians → Degrees", icon: "rad→°", category: "Trigonometry"},
	{id: "arc_length", name: "Arc Length", icon: "s=rθ", category: "Trigonometry"},
	{id: "angular_speed", name: "Angular/Linear Speed", icon: "ω,v", category: "Trigonometry"},
	{id: "right_triangle_defs", name: "Triangle Definitions", icon: "SOH CAH", category: "Trigonometry"},
	{id: "special_triangle", name: "Special Triangles", icon: "30-60-90", category: "Trigonometry"},
	{id: "elev_dep", name: "Elevation/Depression", icon: "∠↑↓", category: "Trigonometry"},
	{id: "reference_angle", name: "Reference Angle", icon: "θ'", category: "Trigonometry"},
	{id: "astc_sign", name: "ASTC Signs", icon: "±", category: "Trigonometry"},
	{id: "sum_diff", name: "Sum/Difference", icon: "sin(A±B)", category: "Trigonometry"},
	{id: "double_angle", name: "Double-Angle", icon: "sin2θ", category: "Trigonometry"},
	{id: "half_angle", name: "Half-Angle", icon: "sin(θ/2)", category: "Trigonometry"},
	{id: "polar_to_rect", name: "Polar → Rectangular", icon: "(r,θ)", category: "Trigonometry"},
	{id: "rect_to_polar", name: "Rectangular → Polar", icon: "R→P", category: "Trigonometry"},
	{id: "polar_distance", name: "Polar Distance", icon: "dist", category: "Trigonometry"},
	{id: "polar_graph", name: "Polar Graphs", icon: "r=f(θ)", category: "Trigonometry"},
	{id: "parametric_to_cartesian", name: "Parametric → Cartesian", icon: "x=f(t)", category: "Trigonometry"},
	{id: "parametric_motion", name: "Parametric Motion", icon: "projectile", category: "Trigonometry"},
	{id: "complex_polar", name: "Complex Polar Form", icon: "r cis θ", category: "Trigonometry"},
	{id: "complex_mult_div", name: "Complex ×/÷", icon: "z1·z2", category: "Trigonometry"},
	{id: "demoivre", name: "De Moivre", icon: "(r cisθ)ⁿ", category: "Trigonometry"},
	{id: "complex_roots", name: "Complex Roots", icon: "ⁿ√z", category: "Trigonometry"},
	// Discrete Math
	{id: "perm", name: "Permutation", icon: "P", category: "Discrete Math"},
	{id: "comb", name: "Combination", icon: "C", category: "Discrete Math"},
	{id: "prob", name: "Probability", icon: "%", category: "Discrete Math"},
	{id: "stats", name: "Statistics", icon: "σ", category: "Discrete Math"},
	{id: "arithmetic_sequence", name: "Arithmetic Seq", icon: "aₙ", category: "Discrete Math"},
	{id: "geometric_sequence", name: "Geometric Seq", icon: "a·rⁿ", category: "Discrete Math"},
	{id: "sequence_limit", name: "Sequence Limits", icon: "seq→", category: "Discrete Math"},
	{id: "infinite_series", name: "Infinite Series", icon: "∑∞", category: "Discrete Math"},
	{id: "induction", name: "Induction", icon: "n→n+1", category: "Discrete Math"},
	{id: "binomial", name: "Binomial Theorem", icon: "(a+b)ⁿ", category: "Discrete Math"},
	// Geometry
	{id: "area_circle", name: "Area of Circle", icon: "◯ A", category: "Geometry"},
	{id: "pythag", name: "Pythagorean Theorem", icon: "△", category: "Geometry"},
	{id: "volume_sphere", name: "Volume of Sphere", icon: "○", category: "Geometry"},
	{id: "parabola", name: "Parabola", icon: "⤵", category: "Geometry"},
	{id: "ellipse", name: "Ellipse", icon: "⬭", category: "Geometry"},
	{id: "hyperbola", name: "Hyperbola", icon: "⤴", category: "Geometry"},
	{id: "polar_conics", name: "Polar Conics", icon: "r(θ)", category: "Geometry"},
	{id: "coord3d", name: "3D Coordinates", icon: "(x,y,z)", category: "Geometry"},
	{id: "sphere_eq", name: "Sphere Equation", icon: "○ E", category: "Geometry"},
	{id: "line_plane_3d", name: "Lines & Planes 3D", icon: "L+P", category: "Geometry"},
];

export let scopeTopics = {
	simple: ["add","subtrt","mult","divid"],
	algebra: [
		"add","basic_funcs","cartesian","circle_eq","comb","complex_mult_div","complex_polar","complex_roots","complex_zeros","coord3d","cos","demoivre","divid","elev_dep","exp","exp_model","fact","finance","func_ops","func_props","inverse_funcs","line3d","line_plane_3d","linear_special","log","mult","parabola","perm","plane3d","poly_ineq","polar_to_rect","power_model","prob","pythag","rational_analysis","rational_eq","rect_to_polar","right_triangle_defs","root","ser","sin","special_triangle","sphere_eq","stats","subtrt","tan","transformations","volume_sphere",
		"fraction","percent","ratio","unit_conv","expr_eval","number_sets","properties","order_ops",
		"linear_word","radical_simplify","radical_eq","rational_exp","exp_rules","sci_notation","complex_basic","variation",
		// New algebra topics
		"linear_eq","quadratic_eq","linear_ineq","quadratic_ineq","rational_ineq","system2x2","poly_ops","poly_div","factoring","func_concepts","linear_graph","nonlinear_graph"
	],
	precalc: [
		"add","subtrt","mult","divid","root","log","exp","fact","ser",
		"perm","comb","prob","sin","cos","tan","cosec","sec","cot","stats",
		"trig_graph","mtrx","vctr","area_circle","pythag","volume_sphere",
		"real_ops","cartesian","circle_eq","linear_special","rational_eq",
		"poly_ineq","func_props","basic_funcs","func_ops","inverse_funcs",
		"transformations","power_model","poly_end","synth_div","complex_zeros",
		"rational_analysis","logistic","exp_model","log_model","finance",
		"parabola","ellipse","hyperbola","polar_conics","coord3d","sphere_eq",
		"line_plane_3d","arithmetic_sequence","geometric_sequence","sequence_limit",
		"infinite_series","induction","binomial","system3x3","row_echelon3x3",
		"partial_fractions","linear_programming","vector3d","line3d","plane3d",
		"deg_to_rad","rad_to_deg","arc_length","angular_speed",
		"right_triangle_defs","special_triangle","elev_dep","reference_angle",
		"astc_sign","sum_diff","double_angle","half_angle","polar_to_rect",
		"rect_to_polar","polar_distance","polar_graph","parametric_to_cartesian",
		"parametric_motion","complex_polar","complex_mult_div","demoivre",
		"complex_roots",
		"fraction","percent","ratio","unit_conv","expr_eval","number_sets","properties","order_ops",
		"linear_word","radical_simplify","radical_eq","rational_exp","exp_rules","sci_notation","complex_basic","variation",
		// New precalc topics
		"linear_eq","quadratic_eq","linear_ineq","quadratic_ineq","rational_ineq","system2x2","poly_ops","poly_div","factoring","func_concepts","linear_graph","nonlinear_graph"
	],
	calc: [
		"add","subtrt","mult","divid","root","log","exp","fact","ser",
		"perm","comb","prob","deri","inte","lim","relRates","limits_continuity",
		"applications_diff","integration_advanced","graphical_calculus",
		"parametric_polar","sequences_series","mtrx","vctr","area_circle",
		"pythag","volume_sphere"
	],
	all: topics.map(t=>t.id)
};
export const SESSION_STORAGE_KEY="mentalSessionSnapshot";