import * as Algebra from "../modules/Algebra/index";
import * as Arithmetic from "../modules/Arithmetic/index";
import * as Calculus from "../modules/Calculus/index";
import * as DiscreteMathematics from "../modules/DiscreteMathematics/index";
import * as LinearAlgebra from "../modules/LinearAlgebra/index";
import * as Trigonometry from "../modules/Trigonometry/index";
import * as Geometry from "../modules/Geometry/index";
import * as dom from "./dom";

const generators: Record<string, (difficulty: string)=>void>={
	add: Arithmetic.generateAddition,
	subtrt: Arithmetic.generateSubtraction,
	mult: Arithmetic.generateMultiplication,
	divid: Arithmetic.generateDivision,
	root: Algebra.generateRoot,
	log: Algebra.generateLogarithm,
	exp: Algebra.generateExponent,
	fact: Algebra.generateFactorial,
	ser: Algebra.generateSeries,
	real_ops: Algebra.generateRealNumberOperations,
	cartesian: Algebra.generateCartesianConcepts,
	circle_eq: Algebra.generateCircleEquations,
	linear_special: Algebra.generateLinearEquationSpecial,
	rational_eq: Algebra.generateRationalEquation,
	poly_ineq: Algebra.generatePolynomialInequality,
	func_props: Algebra.generateFunctionProperties,
	basic_funcs: Algebra.generateBasicFunctions,
	func_ops: Algebra.generateFunctionOperations,
	inverse_funcs: Algebra.generateInverseFunctions,
	transformations: Algebra.generateTransformations,
	power_model: Algebra.generatePowerFunctionModeling,
	poly_end: Algebra.generatePolynomialEndBehavior,
	synth_div: Algebra.generateSyntheticDivision,
	complex_zeros: Algebra.generateComplexZeros,
	rational_analysis: Algebra.generateRationalGraphAnalysis,
	logistic: Algebra.generateLogisticFunctions,
	exp_model: Algebra.generateExponentialModeling,
	log_model: Algebra.generateLogarithmicModeling,
	finance: Algebra.generateFinance,
	fraction: Algebra.generateFraction,
	percent: Algebra.generatePercent,
	ratio: Algebra.generateRatioProportion,
	unit_conv: Algebra.generateUnitConversion,
	expr_eval: Algebra.generateExpressionEvaluation,
	number_sets: Algebra.generateNumberSets,
	properties: Algebra.generateProperties,
	order_ops: Algebra.generateOrderOfOperations,
	linear_word: Algebra.generateLinearWordProblem,
	radical_simplify: Algebra.generateRadicalSimplify,
	radical_eq: Algebra.generateRadicalEquation,
	rational_exp: Algebra.generateRationalExponents,
	exp_rules: Algebra.generateExponentRules,
	sci_notation: Algebra.generateScientificNotation,
	complex_basic: Algebra.generateComplex,
	variation: Algebra.generateVariation,
	deri: Calculus.generateDerivative,
	inte: Calculus.generateIntegral,
	lim: Calculus.generateLimit,
	relRates: Calculus.generateRelatedRates,
	limits_continuity: Calculus.generateLimitsContinuity,
	applications_diff: Calculus.generateApplicationsDiff,
	integration_advanced: Calculus.generateIntegrationAdvanced,
	graphical_calculus: Calculus.generateGraphicalCalculus,
	parametric_polar: Calculus.generateParametricPolarVector,
	sequences_series: Calculus.generateSequencesSeries,
	mtrx: LinearAlgebra.generateMatrix,
	vctr: LinearAlgebra.generateVector,
	system3x3: LinearAlgebra.generateSystem3x3,
	row_echelon3x3: LinearAlgebra.generateRowEchelon3x3,
	partial_fractions: LinearAlgebra.generatePartialFractions,
	linear_programming: LinearAlgebra.generateLinearProgramming,
	vector3d: LinearAlgebra.generateVector3D,
	line3d: LinearAlgebra.generateLine3D,
	plane3d: LinearAlgebra.generatePlane3D,
	sin: Trigonometry.generateSin,
	cos: Trigonometry.generateCosine,
	tan: Trigonometry.generateTangent,
	cosec: Trigonometry.generateCosecant,
	sec: Trigonometry.generateSecant,
	cot: Trigonometry.generateCotangent,
	trig_graph: Trigonometry.generateTrigGraphs,
	deg_to_rad: Trigonometry.generateDegreesToRadians,
	rad_to_deg: Trigonometry.generateRadiansToDegrees,
	arc_length: Trigonometry.generateArcLength,
	angular_speed: Trigonometry.generateAngularLinearSpeed,
	right_triangle_defs: Trigonometry.generateRightTriangleDefs,
	special_triangle: Trigonometry.generateSpecialTriangle,
	elev_dep: Trigonometry.generateElevationDepression,
	reference_angle: Trigonometry.generateReferenceAngle,
	astc_sign: Trigonometry.generateASTCSign,
	sum_diff: Trigonometry.generateSumDifference,
	double_angle: Trigonometry.generateDoubleAngle,
	half_angle: Trigonometry.generateHalfAngle,
	polar_to_rect: Trigonometry.generatePolarToRectangular,
	rect_to_polar: Trigonometry.generateRectangularToPolar,
	polar_distance: Trigonometry.generatePolarDistance,
	polar_graph: Trigonometry.generatePolarGraphEquation,
	parametric_to_cartesian: Trigonometry.generateParametricToCartesian,
	parametric_motion: Trigonometry.generateParametricMotion,
	complex_polar: Trigonometry.generateComplexPolarForm,
	complex_mult_div: Trigonometry.generateComplexMultiplyDivide,
	demoivre: Trigonometry.generateDeMoivre,
	complex_roots: Trigonometry.generateComplexRoots,
	perm: DiscreteMathematics.generatePermutation,
	comb: DiscreteMathematics.generateCombination,
	prob: DiscreteMathematics.generateProbability,
	stats: DiscreteMathematics.generateStatistics,
	arithmetic_sequence: DiscreteMathematics.generateArithmeticSequence,
	geometric_sequence: DiscreteMathematics.generateGeometricSequence,
	sequence_limit: DiscreteMathematics.generateSequenceLimit,
	infinite_series: DiscreteMathematics.generateInfiniteGeometricSeries,
	induction: DiscreteMathematics.generateMathematicalInduction,
	binomial: DiscreteMathematics.generateBinomialTheorem,
	area_circle: Geometry.generateAreaCircle,
	pythag: Geometry.generatePythagorean,
	volume_sphere: Geometry.generateVolumeSphere,
	parabola: Geometry.generateParabola,
	ellipse: Geometry.generateEllipse,
	hyperbola: Geometry.generateHyperbola,
	polar_conics: Geometry.generatePolarConic,
	coord3d: Geometry.generate3DDistanceMidpoint,
	sphere_eq: Geometry.generateSphereEquation,
	line_plane_3d: Geometry.generateLinePlane3D,
	// Newly added generators
	linear_eq: Algebra.generateLinearEquation,
	quadratic_eq: Algebra.generateQuadraticEquation,
	linear_ineq: Algebra.generateLinearInequality,
	quadratic_ineq: Algebra.generateQuadraticInequality,
	rational_ineq: Algebra.generateRationalInequality,
	system2x2: Algebra.generateSystem2x2,
	poly_ops: Algebra.generatePolynomial,
	poly_div: Algebra.generatePolynomialDivision,
	factoring: Algebra.generateFactoring,
	func_concepts: Algebra.generateFunctionConcepts,
	linear_graph: Algebra.generateLinearGraphing,
	nonlinear_graph: Algebra.generateNonLinearGraphing,
};

export function generateQuestion(topicId: string, difficulty: string): void{
	const generator=generators[topicId];
	if (generator){
		generator(difficulty);
	}
	else{
		if (dom.questionArea) dom.questionArea.innerHTML=`<div class="empty-state"><p>Unknown topic</p></div>`;
	}
}